# Generated by Django 2.0.6 on 2019-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.CharField(default='f', max_length=20),
            preserve_default=False,
        ),
    ]
