# Generated by Django 2.0.6 on 2019-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No movie description available.', max_length=500),
        ),
    ]
