# Generated by Django 2.0.6 on 2019-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPrice',
            field=models.IntegerField(default=-1),
        ),
    ]
